/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Outfit', 'sans-serif'],
        "headline-md": ["Manrope"],
        "label-caps": ["JetBrains Mono"],
        "headline-lg": ["Manrope"],
        "body-lg": ["Manrope"],
        "headline-sm": ["Manrope"],
        "headline-lg-mobile": ["Manrope"],
        "body-md": ["Manrope"]
      },
      colors: {
        "surface-dim": "#d9dadb",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#ffb59a",
        "on-tertiary-container": "#93a09a",
        "surface": "#f8f9fa",
        "outline": "#727973",
        "inverse-surface": "#2e3132",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#bcc9c3",
        "surface-container": "#edeeef",
        "secondary": "#8c4e35",
        "on-primary-fixed": "#002113",
        "secondary-fixed": "#ffdbce",
        "on-surface": "#191c1d",
        "on-secondary-container": "#793f27",
        "surface-container-high": "#e7e8e9",
        "on-secondary": "#ffffff",
        "primary-container": "#1b3b2b",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#121e1a",
        "on-surface-variant": "#424843",
        "on-secondary-fixed": "#380d00",
        "on-tertiary-fixed-variant": "#3d4945",
        "surface-tint": "#456553",
        "on-primary-container": "#83a590",
        "primary-fixed-dim": "#abcfb8",
        "inverse-primary": "#abcfb8",
        "tertiary-fixed": "#d8e6df",
        "primary-fixed": "#c7ebd4",
        "surface-container-lowest": "#ffffff",
        "primary": "#032517",
        "on-secondary-fixed-variant": "#6f3720",
        "surface-bright": "#f8f9fa",
        "tertiary": "#16221e",
        "on-primary-fixed-variant": "#2d4d3c",
        "background": "#f8f9fa",
        "inverse-on-surface": "#f0f1f2",
        "surface-container-low": "#f3f4f5",
        "secondary-container": "#ffad8f",
        "error": "#ba1a1a",
        "on-primary": "#ffffff",
        "on-background": "#191c1d",
        "tertiary-container": "#2b3733",
        "surface-container-highest": "#e1e3e4",
        "surface-variant": "#e1e3e4",
        "outline-variant": "#c1c8c2"
      },
      fontSize: {
        "headline-md": ["28px", {"lineHeight": "1.3", "fontWeight": "700"}],
        "label-caps": ["12px", {"lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "500"}],
        "headline-lg": ["40px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-sm": ["20px", {"lineHeight": "1.4", "fontWeight": "600"}],
        "headline-lg-mobile": ["32px", {"lineHeight": "1.2", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
